{% set name = "diffusers" %}
{% set version = "0.35.2" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30ecd552303edfcfe1724573c3918a8462ee3ab4d529bdbd4c0045f763affded

build:
  number: 0
  skip: true  # [py<38]

outputs:
  - name: {{ name }}-base
    script: build_base.sh  # [not win]
    script: build_base.bat  # [win]
    build:
      entry_points:
        - diffusers-cli=diffusers.commands.diffusers_cli:main
      skip: true  # [py<38]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - importlib-metadata
        - filelock
        - huggingface_hub >=0.34.0
        - numpy
        - regex !=2019.12.17
        - requests
        - safetensors >=0.3.1
        - pillow
      run_constrained:
        - huggingface_accelerate >=0.31.0
        - protobuf >=3.20.3,<4
        - peft >=0.17.0
        - pytorch >=1.4
    test:
      imports:
        - diffusers
        - diffusers.models
      commands:
        - pip check
      requires:
        - pip
  - name: diffusers-torch
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - pytorch {{ pytorch }}
      run:
        - python
        - {{ pin_subpackage(name+'-base', exact=True) }}
        - pytorch >=1.4
        - huggingface_accelerate >=0.31.0
    test:
      imports:
        - diffusers
        - diffusers.models
      commands:
        - pip check
        # the diffusers-cli command requires pytorch at runtime,
        # https://github.com/huggingface/diffusers/blob/main/src/diffusers/commands/fp16_safetensors.py#L27
        - diffusers-cli --help
      requires:
        - pip
  ## TODO: Enable once the flax toolchain is flushed out.
  # - name: diffusers-flax
  #   script: build_base.sh  # [not win]
  #   build:
  #     skip: true  # [win]
  #   requirements:
  #     host:
  #       - pip
  #       - python
  #       - setuptools
  #       - wheel
  #     run:
  #       - {{ pin_subpackage(name+'-base', exact=True) }}
  #       - jax >=0.2.8,!=0.3.2
  #       - jaxlib >=0.1.65
  #       - flax
  #   test:
  #     imports:
  #       - diffusers
  #       - diffusers.models
  #     commands:
  #       - pip check
  #       - diffusers-cli --help
  #     requires:
  #       - pip
  - name: diffusers
    build:
      skip: true  # [py<38]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage(name+'-torch', exact=True) }}
    test:
      imports:
        - diffusers
        - diffusers.models
      commands:
        - pip check
        - diffusers-cli --help
      requires:
        - pip

about:
  home: https://github.com/huggingface/diffusers
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Diffusers provides pretrained vision diffusion models, and serves as a modular toolbox for inference and training.
  description: |
    :hugs: Diffusers provides pretrained diffusion models across multiple modalities,
    such as vision and audio, and serves as a modular toolbox for inference and
    training of diffusion models.

    PyPI: [https://pypi.org/project/diffusers/](https://pypi.org/project/diffusers/)

  doc_url: https://huggingface.co/docs/diffusers/index
  dev_url: https://github.com/huggingface/diffusers

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - anton-l
    - patrickvonplaten
