{% set name = "diffusers" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diffusers-{{ version }}.tar.gz
  sha256: fb814ffd150cc6f470380b8c6a521181a77beb2f44134d2aad2e4cd8aa2ced0e

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - filelock
    - huggingface_hub
    - importlib-metadata
    - numpy
    - pillow
    - regex !=2019.12.17
    - requests
    - pytorch >=1.4

test:
  imports:
    - diffusers
    - diffusers.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/diffusers
  license: Apache-2.0
  license_file: LICENSE
  license_family: "Apache"
  license_url: https://github.com/huggingface/diffusers/blob/v{{ version }}/LICENSE
  summary: Diffusers provides pretrained vision diffusion models, and serves as a modular toolbox for inference and training.
  description: |
    :hugs: Diffusers provides pretrained diffusion models across multiple modalities, 
    such as vision and audio, and serves as a modular toolbox for inference and 
    training of diffusion models.

    PyPI: [https://pypi.org/project/diffusers/](https://pypi.org/project/diffusers/)

  doc_url: https://huggingface.co/docs/diffusers/index
  doc_source_url: https://github.com/huggingface/diffusers/tree/main/docs/source
  dev_url: https://github.com/huggingface/diffusers

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - anton-l
    - patrickvonplaten
